---
- name: Load OS specific variables
  include_vars: ../vars/debian.yml

- name: Update server
  apt:
    upgrade: full
    update_cache: yes
  register: update

- name: Install Guacamole library requirements
  apt:
    name:
      - libcairo2-dev
      - libjpeg62-dev
      - libpng-dev
      - libossp-uuid-dev
      - libssh-dev
      - "{{ tomcat_name }}"
      - "{{ tomcat_name }}-admin"
      - "{{ tomcat_name }}-user"
      # to compile the intial code
      - autotools-dev
      - libtool
      - autoconf
      - automake
      - gcc
      - make
      - maven
      # for SQL Auth
      - mysql-server
      - mysql-client
      - mysql-common
      - mysql-utilities
      - python-pymysql
      - python3-pymysql
    state: present
    install_recommends: no

- name: Install optional library components
  when: guacamole_recordings | default(true) or guacamole_rdp | default(true) or
        guacamole_kubernetes | default(true) or guacamole_ssh | default(true) or
        guacamole_telnet | default(true) or guacamole_vnc | default(true) or
        guacamole_vorbis | default(true) or guacamole_webp | default(true)
  apt:
    name: |
      [
        {% if guacamole_recordings | default(true) %}
          'libavcodec-dev', 'libavutil-dev', 'libswscale-dev',
        {% endif %}
        {% if guacamole_rdp | default(true) %}
          'libfreerdp-dev',
        {% endif %}
        {% if guacamole_kubernetes | default(true) or guacamole_ssh | default(true) or guacamole_telnet | default(true) %}
          'libpango1.0-dev',
        {% endif %}
        {% if guacamole_ssh | default(true) %}
          'libssh2-1-dev',
        {% endif %}
        {% if guacamole_telnet | default(true) %}
          'libtelnet-dev',
        {% endif %}
        {% if guacamole_vnc | default(true) %}
          'libvncserver-dev',
          'libpulse-dev',
        {% endif %}
        {% if guacamole_kubernetes | default(true) %}
          'libwebsockets-dev',
        {% endif %}
        {% if guacamole_kubernetes | default(true) or guacamole_ssh | default(true) %}
          'libssl-dev',
        {% endif %}
        {% if guacamole_vorbis | default(true) %}
          'libvorbis-dev',
        {% endif %}
        {% if guacamole_webp | default(true) %}
          'libwebp-dev',
        {% endif %}
      ]
    state: present

- name: "Start MySQL"
  service:
    name: mysql
    state: started
    enabled: yes

- name: Get Debian MySQL System Account file
  slurp:
    src: /etc/mysql/debian.cnf
  register: mysql_creds

- name: Load Debian MySQL System Facts
  set_fact:
    guacamole_db_root_file: /etc/mysql/debian.cnf
    guacamole_db_root_user: |-
      {% set ns=namespace() %}
      {%- for myline in (mysql_creds['content'] | b64decode).splitlines() -%}
        {%- if 'user' in myline -%}
          {%- set ns.mydata=myline | regex_replace('^user\s*=\s*','') | regex_replace('\s+$', '') -%}
        {%- endif -%}
      {%- endfor -%}
      {{ ns.mydata | default('') }}
    guacamole_db_root_password: |-
      {% set ns=namespace() %}
      {%- for myline in (mysql_creds['content'] | b64decode).splitlines() -%}
        {%- if 'password' in myline -%}
          {%- set ns.mydata=myline | regex_replace('^password\s*=\s*','') | regex_replace('\s+$', '') -%}
        {%- endif -%}
      {%- endfor -%}
      {{ ns.mydata | default('') }}
