---
- name: Load OS specific variables
  include_vars: ../vars/debian.yml
  
- name: Update server
  apt:
    upgrade: full
    update_cache: yes
  register: update

- name: Install Guacamole library requirements
  apt:
    name:
      - libcairo2-dev
      - libjpeg62-dev
      - libpng-dev
      - libossp-uuid-dev
      - libfreerdp-dev
      - libpango1.0-dev
      - libssh2-1-dev
      - libssh-dev
      - tomcat9
      - tomcat9-admin
      - tomcat9-user
      - haveged # fixes /dev/random issue
      # to compile the intial code
      - autotools-dev
      - autoconf
      - automake
      - gcc
      - make
      # for SQL Auth
      - mysql-server
      - mysql-client
      - mysql-common
      - mysql-utilities
      - python-pymysql
      - python3-pymysql
    state: present
    install_recommends: no      

- name: "Start MySQL"
  service:
    name: mysql
    state: started
    enabled: yes

- name: Get Debian MySQL System Account file
  slurp:
    src: /etc/mysql/debian.cnf
  register: mysql_creds

- name: Load Debian MySQL System Facts
  set_fact:
    db_admin_user: |-
      {%- set ns = namespace() -%}
      {%- for line in mysql_creds.content.splitlines() -%}
        {%- if ns.user == '' -%}
          {%- if "user" in line -%}
            {%- set ns.user = line | regex_replace('^\s*user\s*=\s*(.*)\s*', '\1') -%}
          {%- endif -%}
        {%- endif -%}
      {%- endfor -%}
      {{ ns.user }}
    db_admin_password: |-
      {%- set ns = namespace() -%}
      {%- for line in mysql_creds.content.splitlines() -%}
        {%- if ns.password == '' -%}
          {%- if "password" in line -%}
            {%- set ns.password = line | regex_replace('^\s*password\s*=\s*(.*)\s*', '\1') -%}
          {%- endif -%}
        {%- endif -%}
      {%- endfor -%}
      {{ ns.password }}