---
- name: "restart_tomcat"
  service:
    name: "{{ tomcat_ver }}"
    state: restarted
    enabled: true

- name: "restart_guacd"
  service:
    name: guacd
    state: restarted
    enabled: true

- name: "restart_mysql"
  service:
    name: "{{ mysql_service }}"
    state: restarted
    enabled: true


